### ISSUE TITLE
App MultipleChoiceOption should appear "blue" on hover

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/discretemath.ca#147]
Please style the [MultipleChoiceOption component](https://github.com/CarletonComputerScienceSociety/discretemath.ca/blob/fa18264cfea58b0406ffbfce4d0b333c90140aa3/app/src/apps/Test/components/MultipleChoiceOption/MultipleChoiceOption.svelte) to have a background color of `#edfeff` on hover.

<img width="524" alt="Screenshot 2022-06-11 at 3 50 08 PM" src="https://user-images.githubusercontent.com/43223682/173202792-32857a34-0b34-4f05-a1fa-6fdd66dbf748.png">

**Comment by theanjali-2002** [comment]
The task is done. Waiting for the review and any other feedback you have.
