### ISSUE TITLE
Implement Drill Class

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/discretemath.ca#152]
Please implement the Drill class. Comments on this fire describe what makes a drill unique.

https://github.com/CarletonComputerScienceSociety/discretemath.ca/blob/master/app/src/apps/Examinations/lib/examinations/Drill.js

**Comment by RohanSreelesh** [comment]
PR open here: https://github.com/CarletonComputerScienceSociety/discretemath.ca/pull/160
