### ISSUE TITLE
Implement MultipleChoiceQuestion Class

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/discretemath.ca#155]
Please complete the MultipleChoiceQuestion class. This will require making updates to the Question class.

https://github.com/CarletonComputerScienceSociety/discretemath.ca/blob/9583b05082c1c15fd3fe26b15c667c4316bda88c/app/src/apps/Examinations/lib/questions/MultipleChoiceQuestion.js

**Comment by RohanSreelesh** [comment]
PR open here: https://github.com/CarletonComputerScienceSociety/discretemath.ca/pull/160
