### ISSUE TITLE
Create Prototype "guides" app

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/discretemath.ca#162]
On discretemath.ca we will want to render markdown formatted guides.

Please update [this component](https://github.com/CarletonComputerScienceSociety/discretemath.ca/blob/198d6f5dbc24669ea101d713c23c8f107044a168/app/src/apps/Guides/Guide.astro) to take markdown as input and render its front matter (title and author) and markdown.

Please get it to take guides "as input". Do not import the .md file within the Guide.astro file. 

I've included [this file](app/src/data/guides/comp2804/test.md) to be used as a demo.

**Comment by andGuo** [comment]
I completed this in #171, please assign to me :)
